### ISSUE TITLE
Supported syntaxes?

### ISSUE THREAD

**Issue by IngwiePhoenix** [bcherny/package-maker#1]
Disclaimer: I haven't tested this tool yet.

Basically, normal require's look like so:

``` javascript
require("microdash");
//      ^^^^^^^^^^^ package name
```

Then, we have WebPack's `require` syntax, that derives from CommonJs:

``` javascript
require(["microdash", "jquery"], function(_, $){ /*...*/});
//       ^^^^^^^^^^^  ^^^^^^^^ package names
require.ensure(["microdash", "jquery"], function(_, $){ /*...*/});
//              ^^^^^^^^^^^  ^^^^^^^^ package names

```

And the same can also be used with the `define` function.

But there is also `import EXPR from STRING`:

``` javascript
import redis from "redis";
//                ^^^^^^^ Name

import {foo, bar} from "baz";
//                     ^^^^^ Name
```

Which of these are supported?

**Comment by bcherny** [comment]
hi there @IngwiePhoenix!

package-maker uses [detective](https://github.com/substack/node-detective), which only supports CommonJS-style `require()`s.

**Comment by IngwiePhoenix** [comment]
Ahh, alright. Thank you anyway! :)
